Add agent image digest to release notes

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -138,6 +138,7 @@ parse_args_and_release() {
       docker push $new_image
       if [[ "$stage" == "final" ]]; then
         update_floating_docker_tags "$new_version" "$new_image" "$image_base"
+        add_digest_to_release "v$new_version" "$new_image" "$image_base" "$github_username" "$github_token"
       fi
     fi
   fi
@@ -392,6 +393,50 @@ release_python_to_pypi() {
   python3 -m twine upload dist/*
 
   popd
+}
+
+add_digest_to_release() {
+  local tag=$1
+  local new_image=$2
+  local image_base=$3
+  local username=$4
+  local token=$5
+  local digest=$(docker inspect --format='{{.RepoDigests}}' $new_image | sed "s|\[${image_base}@\(sha256:.*\)\]|\1|")
+
+  if [[ ! "$digest" =~ ^sha256:[A-Fa-f0-9]{64}$ ]]; then
+    echo "Failed to get manifest digest for $new_image!"
+    exit 1
+  fi
+
+  . $SCRIPT_DIR/github-releases.sh
+
+  release_id=$(github_request "$username" "$token" "GET" "releases" | jq --arg tag "$tag" '.[] | select(.tag_name==$tag) | .id')
+  if [[ ! "$release_id" =~ ^[0-9]+$ ]]; then
+    echo "Failed to get release id for $tag!"
+    exit 1
+  fi
+
+  # get original release message and append the agent image digest
+  body=$(github_request "$username" "$token" "GET" "releases" | jq --argjson id $release_id '.[] | select(.id==$id) | .body' | tr -d '"')
+  if [[ -z "$body" ]]; then
+    echo "Failed to get release message for $tag!"
+    exit 1
+  fi
+
+  body="""$(echo -en $body)
+
+> Docker Image: \`$new_image\` (digest: \`$digest\`)
+"""
+
+  tmpfile=$(mktemp)
+  echo "$tmpfile"
+  cat <<EOH > $tmpfile
+    {
+      "body": $(jq -n --arg body "$body" '$body')
+    }
+EOH
+
+  github_request "$username" "$token" "PATCH" "releases/$release_id" $tmpfile
 }
 
 parse_args_and_release $@
